name: Build All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run formatting check
      run: |
        poetry run black --check .

    - name: Run linting
      run: |
        poetry run flake8 --max-line-length=99 --per-file-ignores=tests/*:F841 --extend-ignore=E203,E501

    - name: Run tests
      run: |
        poetry run pytest