name: Music Pipeline

on:
  workflow_dispatch:
  repository_dispatch:
    types: [music_pipeline]

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run music update script
        run: poetry run python src/tools/music_tag_sort/renamer.py
