name: Process New CSV Files

on:
  workflow_dispatch:
  repository_dispatch:
    types: [new_csv_dj_sets]

concurrency:
  group: dj-set-collection
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run process_new_csv_files
        run: poetry run python src/tools/dj_set_processor/process_new_csv_files.py

      - name: Run create_dj_set_collection
        run: poetry run python src/tools/dj_set_processor/dj_set_collection.py
